# Config file for automatic testing at travis-ci.org
language: python
env:
  - FLASK_APP=app.py FLASK_CONFIG=testing ELASTIC_SEARCH_URL=127.0.0.1
python:
  - 3.5
  - 3.6
services:
  - elasticsearch
install:
  - pip install -r fact-bounty-flask/requirements.txt
  - pip install -r Crawlers/requirements.txt
before_script:
  - sleep 10
  - cd Crawlers
  - scrapyd > logfile_scrapy &
  - cd ..
  - python db/add_es.py
script: 
  - cd fact-bounty-flask
  - flask test
