version: '3'

services:
  flask_server:
    build: ./fact-bounty-flask
    ports:
      - 5000:5000
    restart: always
    links:
      - mysql:dbserver

  client:
    build: ./fact-bounty-client
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development

  mysql:
    image: "mysql/mysql-server:5.7"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
